export const carColumns = [
  { field: "id", headerName: "ID", flex: 1 },
  {
    field: "category",
    headerName: "Category",
    type: "singleSelect",
    valueOptions: [
      "Bulgaria",
      "Netherlands",
      "France",
      "United Kingdom",
      "Spain",
      "Brazil",
    ],
    flex: 1,
    editable: true,
  },
  { field: "company", headerName: "Company", flex: 1, editable: true },
  { field: "name", headerName: "Name", flex: 1, editable: true },
  { field: "color", headerName: "Color", flex: 1, editable: true },
  { field: "model", headerName: "Model", flex: 1, editable: true },
  {
    field: "registrationNo",
    headerName: "Registration No",
    flex: 1,
    editable: true,
  },
];

export const carRows = [
  {
    id: 1,
    category: "Bus",
    company: "Honda",
    name: "civic",
    color: "red",
    model: "2012",
    registrationNo: "98709",
  },

  {
    id: 2,
    category: "Bus",
    company: "Honda",
    name: "civic",
    color: "red",
    model: "2012",
    registrationNo: "98709",
  },
  {
    id: 3,
    category: "Bus",
    company: "Honda",
    name: "civic",
    color: "red",
    model: "2012",
    registrationNo: "98709",
  },
  {
    id: 4,
    category: "Bus",
    company: "Honda",
    name: "civic",
    color: "red",
    model: "2012",
    registrationNo: "98709",
  },
  {
    id: 5,
    category: "Bus",
    company: "Honda",
    name: "civic",
    color: "red",
    model: "2012",
    registrationNo: "98709",
  },
];
