export const carColumns = [
  { field: "id", headerName: "ID", flex: 1 },
  {
    field: "category",
    headerName: "Category",
    type: "singleSelect",

    valueOptions: [
      "Bulgaria",
      "Netherlands",
      "France",
      "United Kingdom",
      "Spain",
      "Brazil",
    ],
    flex: 1,
    editable: true,
  },
  { field: "color", headerName: "Color", flex: 1, editable: true },
  { field: "model", headerName: "Model", flex: 1, editable: true },
  {
    field: "registrationNo",
    headerName: "Registration No",
    flex: 1,
    editable: true,
  },
  { field: "owner", headerName: "Owner", flex: 1, editable: true },
];

export const carRows = [
  {
    id: 1,
    category: "Bus",
    color: "red",
    model: "2012",
    registrationNo: "98709",
    owner: "Ameen",
  },
  {
    id: 2,
    category: "Hatchback",
    color: "red",
    model: "2012",
    registrationNo: "98709",
    owner: "Ameen",
  },
  {
    id: 3,
    category: "Sedan",
    color: "red",
    model: "2012",
    registrationNo: "98709",
    owner: "Ameen",
  },
  {
    id: 4,
    category: "SUV",
    color: "red",
    model: "2012",
    registrationNo: "98709",
    owner: "Ameen",
  },
  {
    id: 5,
    category: "Hatchback",
    color: "red",
    model: "2012",
    registrationNo: "98709",
    owner: "Ameen",
  },
  {
    id: 6,
    category: "Jeep",
    color: "red",
    model: "2012",
    registrationNo: "98709",
    owner: "Ameen",
  },
  {
    id: 7,
    category: "Sedan",
    color: "red",
    model: "2012",
    registrationNo: "98709",
    owner: "Ameen",
  },
  {
    id: 8,
    category: "SUV",
    color: "red",
    model: "2012",
    registrationNo: "98709",
    owner: "Ameen",
  },
];
